services:
  - docker

before_install:
  - docker build -t tracker -f docker/Dockerfile
  - docker run -d -p 127.0.0.1:8000:8000 tracker /bin/sh -c "cd /opt/tracker; python manage.py runserver;"
  - docker ps -a
