# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('First Name', models.CharField(max_length=32)),
                ('Last Name', models.CharField(max_length=32)),
                ('E-mail', models.CharField(max_length=32)),
                ('Phone number', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=128)),
                ('Birth date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User'),
        ),
    ]
